package ps.leic.isel.pt.gis.utils

object ExtraUtils {

    const val HOUSE_NAME: String = "HOUSE-NAME"
    const val PRODUCT: String = "PRODUCT"
    const val CATEGORIES: String = "CATEGORIES"
    const val CATEGORY_ID: String = "CATEGORY-ID"
    const val CATEGORY_NAME: String = "CATEGORY-NAME"
    const val PRODUCTS: String = "PRODUCTS"
    const val LISTS: String = "LISTS"
    const val LIST: String = "LIST"
    const val ABOUT: String = "ABOUT"
    const val SETTINGS: String = "SETTINGS"
    const val CATEGORY: String = "CATEGORY"
    const val HOUSE_ID: String = "HOUSE-ID"
    const val STOCK_ITEM: String = "STOCK-ITEM"
    const val SHOW_ALLERGIES: String = "SHOW-ALLERGIES"
    const val ALLERGIES: String = "ALLERGIES"
    const val WRITING_NFC_TAG: String = "WRITING-NFC-TAG"
    const val NFC_MESSAGE: String = "NFC-MESSAGE"
    const val WRITE_NFC_TAG: String = "WRITE-NFC-TAG"
    const val USER_USERNAME: String = "USER-USERNAME"
    const val PROFILE: String = "PROFILE"
    const val INVITATIONS: String = "INVITATIONS"
    const val STORAGES: String = "STORAGES"
    const val STOCK_ITEM_LIST: String = "STOCK-ITEM-LIST"
    const val PROFILE_PAGE: String = "PROFILE-PAGE"
    const val HOME_PAGE: String = "HOME-PAGE"
    const val NEW_LIST_DIALOG: String = "NEW-LIST"
    const val NEW_HOUSE_DIALOG: String = "NEW-HOUSE"
    const val URL: String = "URL"
    const val LIST_NAME: String = "LIST_NAME"
    const val PRODUCT_NAME: String = "PRODUCT_NAME"
    const val VARIETY: String = "VARIETY"
    const val BASIC_INFORMATION_URL: String = "basic_information_url"
    const val HOUSE_URL: String = "house_url"
}